package main

import rl "vendor:raylib"

DEV :: true
DESKTOP :: true

SURFACE_WIDTH :: 480
SURFACE_HEIGHT :: 270

CHUNK_WIDTH :: 100
CHUNK_HEIGHT :: 100
CHUNK_RENDER_DISTANCE_X :: 2
CHUNK_RENDER_DISTANCE_Y :: 2
