package main

import rl "vendor:raylib"

DEV :: true
DESKTOP :: false

SURFACE_WIDTH :: 480
SURFACE_HEIGHT :: 270

CHUNK_WIDTH :: 8
CHUNK_HEIGHT :: 8
CHUNK_RENDER_DISTANCE_X :: 2
CHUNK_RENDER_DISTANCE_Y :: 2

GRID_SIZE :: 16
ONE_PIXEL :: (1.0 / f32(GRID_SIZE))
